common/models/News.php
<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "news".
 *
 * @property integer $id
 * @property string $page_img_path
 * @property string $page_alias
 * @property string $page_title
 * @property string $page_meta_d
 * @property string $page_meta_k
 * @property string $page_content
 * @property string $page_date
 * @property string $page_publish
 */
class News extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'news';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['page_title', 'page_meta_d', 'page_content', 'page_date'], 'required'],
            [['page_meta_d', 'page_meta_k', 'page_content'], 'string'],
            [['page_img_path', 'page_alias', 'page_title', 'page_date'], 'string', 'max' => 255],
            [['page_publish'], 'string', 'max' => 1],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'page_img_path' => Yii::t('app', 'Page Img Path'),
            'page_alias' => Yii::t('app', 'Page Alias'),
            'page_title' => Yii::t('app', 'Page Title'),
            'page_meta_d' => Yii::t('app', 'Page Meta D'),
            'page_meta_k' => Yii::t('app', 'Page Meta K'),
            'page_content' => Yii::t('app', 'Page Content'),
            'page_date' => Yii::t('app', 'Page Date'),
            'page_publish' => Yii::t('app', 'Page Publish'),
        ];
    }
}

backend/controllers/NewsController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\news;
use backend\models\NewsSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * NewsController implements the CRUD actions for news model.
 */
class NewsController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all news models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new NewsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single news model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new news model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new news();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing news model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing news model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the news model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return news the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = news::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

frontend/controllers/NewsController.php
<?php

namespace frontend\controllers;

use yii\web\NotFoundHttpException;

class NewsController extends \yii\web\Controller
{
    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionNewsPage($id)
    {
        return $this->render('news_page', ['id' => $id]);
    }
}

frontend/views/news/_list.php
<?php
use yii\helpers\Html;
use yii\helpers\HtmlPurifier;
use yii\helpers\Url;
?>

<div class="news-item">
    <a href="<?= Url::to(['news/news-page', 'id' => $model->id]);?>" style="text-decoration: none; color: green"><h3><?= Html::encode($model->page_title) ?></h3></a>
    <?= HtmlPurifier::process($model->page_meta_d) ?>
    <p class="pull-right"><?= Html::encode($model->page_date)?></p>
</div>

frontend/views/news/index.php
<?php
/* @var $this yii\web\View */
use common\models\news;
//use yii\helpers\Url;
use yii\widgets\ListView;
use yii\data\ActiveDataProvider;
$this->title = 'Великий Гвинтер | Новости';
?>
<div id="substrate" class="col-md-9">
    <div class="container">
        <h1>Новости</h1>
        <div class="row">
            <div class="container">
                <div class="col-md-8">
                    <div class="content_sector">
                     <?php
                    $dataProvider = new ActiveDataProvider([
                        'query' => News::find()->where(['page_publish'=>'Y'])->orderBy('id DESC'),
                        'pagination' => [
                            'pageSize' => 20,
                        ],
                    ]);

                    echo ListView::widget([
                        'dataProvider' => $dataProvider,
                        'itemView' => '_list',

                        'options' => [
                            'tag' => 'div',
                            'class' => 'news-list',
                            'id' => 'news-list',
                        ],


                        //'layout' => "{pager}\n{summary}\n{items}\n{pager} Показано {count} из {totalCount}",
                        'summary' => '',
                        'summaryOptions' => [
                            'tag' => 'span',
                            'class' => 'my-summary'
                        ],

                        'itemOptions' => [
                            'tag' => 'div',
                            'class' => 'news-item',
                        ],

                        'emptyText' => '<p>Список пуст</p>',
                        'emptyTextOptions' => [
                            'tag' => 'p'
                        ],

                        'pager' => [
                            //'firstPageLabel' => 'Первая',
                            //'lastPageLabel' => 'Последняя',
                            'nextPageLabel' => 'Следующая',
                            'prevPageLabel' => 'Предыдущая',
                            'maxButtonCount' => 3,
                        ],
                    ]);?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

frontend/views/news/news_page.php
<?php
use yii\helpers\Html;
use yii\web\NotFoundHttpException;
//use yii\helpers\HtmlPurifier;
use common\models\News;

$post = News::find()->where(['id' => "$id"])->one();
$this->title = 'Великий Гвинтер | '.$post->page_title;
if($post->page_publish <> 'Y') throw new \yii\web\NotFoundHttpException('Данной страницы не существует');
else {
?>
<div id="substrate" class="col-md-9">
    <div class="row">
        <div class="container" style="padding: 20px 50px 20px 50px; line-height: 30px ">
            <div class="col-md-9">
                <h1><?=Html::encode($post->page_title)?></h1>
                <p><?=$post->page_content?></p>
                <p><?=Html::encode($post->page_date)?></p>
            </div>
        </div>
    </div>
</div>
<?}?>
<!--Yii::$app->formatter->asntext(Html::encode())-->