common/models/Articles.php
<?php

namespace common\models;

use Yii;
use yii\web\UploadedFile;

/**
 * This is the model class for table "articles".
 *
 * @property integer $id
 * @property string $page_img_path
 * @property string $page_alias
 * @property string $page_category
 * @property string $page_title
 * @property string $page_meta_d
 * @property string $page_meta_k
 * @property string $page_content
 * @property string $page_publish
 */
class Articles extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'articles';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['page_title', 'page_meta_d', 'page_content'], 'required'],
            [['page_meta_d', 'page_meta_k', 'page_content'], 'string'],
            [['page_img_path', 'page_alias', 'page_category', 'page_title'], 'string', 'max' => 255],
            [['page_publish'], 'string', 'max' => 1],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'page_img_path' => Yii::t('app', 'Page Img Path'),
            'page_alias' => Yii::t('app', 'Page Alias'),
            'page_category' => Yii::t('app', 'Page Category'),
            'page_title' => Yii::t('app', 'Page Title'),
            'page_meta_d' => Yii::t('app', 'Page Meta D'),
            'page_meta_k' => Yii::t('app', 'Page Meta K'),
            'page_content' => Yii::t('app', 'Page Content'),
            'page_publish' => Yii::t('app', 'Page Publish'),
        ];
    }
}
class UploadForm extends \yii\db\ActiveRecord
    {
    /**
     * @var UploadedFile
     */
    public $imageFile;

    public function rules()
    {
        return [
            [['imageFile'], 'file', 'skipOnEmpty' => false, 'extensions' => 'png, jpg'],
        ];
    }

    public function upload()
    {
        if ($this->validate()) {
            $this->imageFile->saveAs('uploads/' . $this->imageFile->baseName . '.' . $this->imageFile->extension);
            return true;
        } else {
            return false;
        }
    }
}

backend/controllers/ArticlesController.php
<?php
namespace backend\controllers;

use Yii;
use common\models\Articles;
use common\models\UploadForm;
use backend\models\ArticlesSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;
use yii\helpers\BaseFileHelper;
use yii\helpers\Url;


/**
 * ArticlesController implements the CRUD actions for Articles model.
 */
class ArticlesController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Articles models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ArticlesSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Articles model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Articles model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Articles();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Articles model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Articles model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Articles model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Articles the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Articles::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

//    public function actionUpload()
//    {
//        return $this->render('upload');
//    }

    public function actionUpload()
    {
        $model = new UploadForm();

        if (Yii::$app->request->isPost) {
            $model->imageFile = UploadedFile::getInstance($model, 'imageFile');
            if ($model->upload()) {
                echo "Файл успешно загружен";
                return;
            }
        }
        return $this->render('upload', ['model' => $model]);
    }
}

frontend/controllers/ArticlesController.php
<?php

namespace frontend\controllers;

class ArticlesController extends \yii\web\Controller
{
    public function actionIndex()
    {
        return $this->render('index');
    }
    public function actionArticlesPage($alias, $id)
    {
        return $this->render('articles_page', ['alias' => $alias, 'id' => $id]);
    }
}

frontend/views/articles/_list.php
<?php
use yii\helpers\Html;
use yii\helpers\HtmlPurifier;
use yii\helpers\Url;
?>

<div class="articles-item">
    <a href="<?= Url::to(['articles/articles-page', 'id' => $model->id, 'alias' => $model->page_alias]);?>" style="text-decoration: none; color: green">
        <h5><?= Html::encode($model->page_title) ?></h5></a>
<!--    <p class="pull-right">--><?//= Html::encode($model->page_date)?><!--</p>-->
</div>

frontend/views/articles/articles_page.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;

use common\models\Articles;
$post = Articles::find()->where(['id' => "$id"])->one();
$this->title = 'Великий Гвинтер | '.$post->page_title;
    ?>
<div class="row">
    <div class="col-md-9">
        <div class="top-panel">
            <?= Html::img(Url::to('/frontend/web/img/Articles_img.png'), ['alt'=>'picture', 'class'=>'top-panel'])?>
            <h1><?=Html::encode($post->page_title)?></h1>
        </div>
    </div>
</div>
        <div id="substrate" class="col-md-9">
                <?php if($post->page_publish <> 'Y') throw new \yii\web\NotFoundHttpException('Данной страницы не существует');
                else { ?>
                <div class="row">
                    <div class="container" style="padding: 50px 20px 50px 0px; line-height: 30px ">
                        <div class="col-md-9">
                            <p align="justify"><?= $post->page_content?></p>
                            <?php if (isset($post->page_img_path)) { ?>
                            <div class="row">
                                <div class="col-md-12 col-sm-12 col-lg-12" style="">
                                    <?php if(!$post->page_img_path == "") { echo Html::img(Url::to('/backend/web/uploads/' . $post->page_img_path, true), ['alt'=>'picture', 'class'=>'img-thumbnail deck_img']); }?>
                                </div>
                            </div>
                                <?php } ?>
                        </div>
                    </div>
                </div>
        </div>
<?}?>
<!--HTMLPurifier::process(
Yii::$app->formatter->asntext(Html::encode())-->

frontend/views/articles/index.php
<?php
use yii\widgets\ListView;
use yii\data\ActiveDataProvider;
use common\models\Articles;
/* @var $this yii\web\View */
$this->title = 'Великий Гвинтер | Статьи';
?>
<div id="substrate" class="col-md-9">
        <h1>Статьи</h1>
        <div class="row">
            <div class="container" style="padding: 50px 30px 50px 0px;">
            <div class="col-md-3">
            <div class="panel panel-success">
                <div class="panel-heading">Основы</div>
                <div class="panel-body">
                    <?php
                    $dataProvider = new ActiveDataProvider([
                        'query' => Articles::find()->where(['page_publish'=>'Y', 'page_category'=>'learning'])->orderBy('id'),
                        'pagination' => [
                            'pageSize' => 30,
                        ],
                    ]);

                    echo ListView::widget([
                        'dataProvider' => $dataProvider,
                        'itemView' => '_list',

                        'options' => [
                            'tag' => 'div',
                            'class' => 'decks-list',
                            'id' => 'decks-list',
                        ],


                        //'layout' => "{pager}\n{summary}\n{items}\n{pager} Показано {count} из {totalCount}",
                        'summary' => '',
                        'summaryOptions' => [
                            'tag' => 'span',
                            'class' => 'my-summary'
                        ],

                        'itemOptions' => [
                            'tag' => 'div',
                            'class' => 'news-item',
                        ],

                        'emptyText' => '<p>Список пуст</p>',
                        'emptyTextOptions' => [
                            'tag' => 'p'
                        ],

    //                'pager' => [
    //                    //'firstPageLabel' => 'Первая',
    //                    //'lastPageLabel' => 'Последняя',
    //                    'nextPageLabel' => 'Следующая',
    //                    'prevPageLabel' => 'Предыдущая',
    //                    'maxButtonCount' => 3,
    //                ],
                    ]);
                    ?>
                    </div>
                 </div>
            </div>
                <div class="col-md-3">
                    <div class="panel panel-success">
                        <div class="panel-heading">Тонкости игры</div>
                        <div class="panel-body">
                            <?php
                            $dataProvider = new ActiveDataProvider([
                                'query' => Articles::find()->where(['page_publish'=>'Y', 'page_category'=>'advanced'])->orderBy('id DESC'),
                                'pagination' => [
                                    'pageSize' => 30,
                                ],
                            ]);

                            echo ListView::widget([
                                'dataProvider' => $dataProvider,
                                'itemView' => '_list',

                                'options' => [
                                    'tag' => 'div',
                                    'class' => 'decks-list',
                                    'id' => 'decks-list',
                                ],


                                //'layout' => "{pager}\n{summary}\n{items}\n{pager} Показано {count} из {totalCount}",
                                'summary' => '',
                                'summaryOptions' => [
                                    'tag' => 'span',
                                    'class' => 'my-summary'
                                ],

                                'itemOptions' => [
                                    'tag' => 'div',
                                    'class' => 'news-item',
                                ],

                                'emptyText' => '<p>Список пуст</p>',
                                'emptyTextOptions' => [
                                    'tag' => 'p'
                                ],

    //                'pager' => [
    //                    //'firstPageLabel' => 'Первая',
    //                    //'lastPageLabel' => 'Последняя',
    //                    'nextPageLabel' => 'Следующая',
    //                    'prevPageLabel' => 'Предыдущая',
    //                    'maxButtonCount' => 3,
    //                ],
                            ]);
                            ?>
                        </div>
                    </div>
                </div>
                    <div class="col-md-3">
                        <div class="panel panel-success">
                            <div class="panel-heading">Остальное</div>
                            <div class="panel-body">
                                <?php
                                $dataProvider = new ActiveDataProvider([
                                    'query' => Articles::find()->where(['page_publish'=>'Y', 'page_category'=>'other'])->orderBy('id DESC'),
                                    'pagination' => [
                                        'pageSize' => 30,
                                    ],
                                ]);

                                echo ListView::widget([
                                    'dataProvider' => $dataProvider,
                                    'itemView' => '_list',

                                    'options' => [
                                        'tag' => 'div',
                                        'class' => 'decks-list',
                                        'id' => 'decks-list',
                                    ],


                                    //'layout' => "{pager}\n{summary}\n{items}\n{pager} Показано {count} из {totalCount}",
                                    'summary' => '',
                                    'summaryOptions' => [
                                        'tag' => 'span',
                                        'class' => 'my-summary'
                                    ],

                                    'itemOptions' => [
                                        'tag' => 'div',
                                        'class' => 'news-item',
                                    ],

                                    'emptyText' => '<p>Список пуст</p>',
                                    'emptyTextOptions' => [
                                        'tag' => 'p'
                                    ],

    //                'pager' => [
    //                    //'firstPageLabel' => 'Первая',
    //                    //'lastPageLabel' => 'Последняя',
    //                    'nextPageLabel' => 'Следующая',
    //                    'prevPageLabel' => 'Предыдущая',
    //                    'maxButtonCount' => 3,
    //                ],
                                ]);
                                ?>
                            </div>
                        </div>
                    </div>
            </div>
    </div>
</div>