common/models/Decks.php
<?php

namespace common\models;

use Yii;
use yii\helpers\BaseUrl;
use yii\web\UploadedFile;

/**
 * This is the model class for table "decks".
 *
 * @property integer $id
 * @property string $deck_faction
 * @property string $deck_name
 * @property string $deck_img_path
 * @property string $deck_version
 * @property string $deck_description
 * @property string $deck_strategy
 * @property string $deck_publish
 */
class Decks extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'decks';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {

        return [
            [['deck_faction', 'deck_name', 'deck_strategy'], 'required'],
            [['deck_description', 'deck_strategy'], 'string'],
            [['deck_faction', 'deck_name', 'deck_img_path', 'deck_version'], 'string', 'max' => 255],
            [['deck_publish'], 'string', 'max' => 1],
        ];

    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'deck_faction' => Yii::t('app', 'Deck Faction'),
            'deck_name' => Yii::t('app', 'Deck Name'),
            'deck_img_path' => Yii::t('app', 'Deck Img Path'),
            'deck_version' => Yii::t('app', 'Deck Version'),
            'deck_description' => Yii::t('app', 'Deck Description'),
            'deck_strategy' => Yii::t('app', 'Deck Strategy'),
            'deck_publish' => Yii::t('app', 'Deck Publish'),
        ];
    }
}

backend/controllers/DecksController.php
<?php

namespace backend\controllers;


use common\models\UploadForm;
use Yii;
use common\models\decks;
use backend\models\DecksSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;


/**
 * DecksController implements the CRUD actions for decks model.
 */
class DecksController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all decks models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new DecksSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single decks model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new decks model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new decks();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing decks model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);


        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing decks model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the decks model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return decks the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = decks::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

frontend/controllers/DecksController.php
<?php

namespace frontend\controllers;

class DecksController extends \yii\web\Controller
{
    public function actionIndex($name)
    {
        return $this->render('index', ['name' => $name]);
    }
    public function actionDecksPage($id)
    {
        return $this->render('decks_page', ['id' => $id]);
    }

}

frontend/views/decks/_list.php
<?php
use yii\helpers\Html;
use yii\helpers\HtmlPurifier;
use yii\helpers\Url;

?>

<div class="decks-item" style="">
        <img id="faction_icon" class="pull-left" style="height: 80%; border-right: black 1px solid; margin: 3px" src="<?= \Yii::$app->request->baseUrl?>/img/<?= $model->deck_faction?>_icon.png"/>
    <div style="">
        <a href="<?= Url::to(['decks/decks-page', 'id' => $model->id])?>" style="text-decoration: none; color: green"><h3><?= Html::encode($model->deck_name) ?>(<?= Html::encode($model->deck_version) ?>)</h3></a>
    </div>
</div>

frontend/views/decks/decks_page.php
<?php
use yii\helpers\Html;
use yii\web\NotFoundHttpException;
use yii\helpers\HtmlPurifier;
use yii\helpers\Url;
use common\models\Decks;

$post = Decks::find()->where(['id' => "$id"])->one();
$this->title = 'Великий Гвинтер | '.$post->deck_name;
if($post->deck_publish <> 'Y') throw new \yii\web\NotFoundHttpException('Данной страницы не существует');
else {
?>
    <div class="block">
        <div id="substrate" class="col-md-9">
            <div class="">
                <h1 style="text-align: center"><?=Html::encode($post->deck_name)?></h1>
            </div>
            <div class="row">
                <div class="col-md-12" style="">
                    <?= Html::img(Url::to('/backend/web/uploads/' . $post->deck_img_path, true), ['alt'=>'Deck picture', 'class'=>'img-thumbnail deck_img'])?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-9">
                    <div class="container" style="padding: 20px 50px 20px 50px">
                        <p><?= $post->deck_strategy?></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="block">
        <div id="substrate_label" class="col-md-3 col-sm-12">
            <div class="row">
                <h3 style="text-align: center">Состав колоды:</h3>
                <div style="border: solid 1px black; border-radius: 5px; margin: 3px; text-align: center">
                    <p><?=$post->deck_description?></p>
                </div>
            </div>
        </div>
    </div>

<?}?>

frontend/views/decks/index.php
<?php
use common\models\decks;
//use yii\helpers\Url;
use yii\widgets\ListView;
use yii\data\ActiveDataProvider;
$this->title = 'Великий Гвинтер | Колоды';
/* @var $this yii\web\View */
?>
<div id="substrate" class="col-md-9">
<div class="container">
    <h1>Колоды</h1>
<?php
switch ($name) {
    case 'northernrealms':
        echo "<h3>Королевства Севера</h3>";
        $icon_path = '/img/icon_northernrealms.png';
        break;
    case 'skellige':
        echo "<h3>Скеллиге</h3>";
        $icon_path = '/img/icon_skellige.png';
        break;
    case 'monsters':
        echo "<h3>Чудовища</h3>";
        $icon_path = '/img/icon_monsters.png';
        break;
    case 'scoiatael':
        echo "<h3>Скоя'таэли</h3>";
        $icon_path = '/img/icon_scoiatael.png';
        break;
    case 'nilfgaard':
        echo "<h3>Нильфгаард</h3>";
        $icon_path = '/img/icon_nilfgaard.png';
        break;
    default:
        throw new \yii\web\NotFoundHttpException();
}
    ?>
        <div class="row">
            <div class="container">
            <div class="col-md-8">
            <div class="content_sector"><?php
    $dataProvider = new ActiveDataProvider([
        'query' => Decks::find()->where(['deck_publish'=>'Y', 'deck_faction'=>$name])->orderBy('id DESC'),
        'pagination' => [
            'pageSize' => 20,
        ],
    ]);

    echo ListView::widget([
        'dataProvider' => $dataProvider,
        'itemView' => '_list',

        'options' => [
            'tag' => 'div',
            'class' => 'decks-list',
            'id' => 'decks-list',
        ],


        //'layout' => "{pager}\n{summary}\n{items}\n{pager} Показано {count} из {totalCount}",
        'summary' => '',
        'summaryOptions' => [
            'tag' => 'span',
            'class' => 'my-summary'
        ],

        'itemOptions' => [
            'tag' => 'div',
            'class' => 'news-item',
        ],

        'emptyText' => '<p>Список пуст</p>',
        'emptyTextOptions' => [
            'tag' => 'p'
        ],

        'pager' => [
            //'firstPageLabel' => 'Первая',
            //'lastPageLabel' => 'Последняя',
            'nextPageLabel' => 'Следующая',
            'prevPageLabel' => 'Предыдущая',
            'maxButtonCount' => 3,
        ],
    ]);
    ?>
                     </div>
                 </div>
            </div>
        </div>
    </div>
</div>